
GET http://10.2.40.208/?servo=on
###
GET http://10.2.40.208/?servo=off


###
GET http://10.2.40.208/?dir=forward
###
GET http://10.2.40.208/?dir=stop

###
GET http://10.2.40.208/?pompe=on

###
GET http://10.2.40.208/?pompe=off